package feishu

import (
	"errors"
	"github.com/chenhg5/cc-connect/core"
	"strings"
)

type cardInteraction struct {
	messageID string
	binding   core.CardInteraction
	actions   map[string]map[string]string
}

// Only the latest question per session is useful. Values come from the card
// generated by core, never from a callback's supplied labels or session key.
func (p *Platform) bindInteraction(messageID string, rc replyContext, card *core.Card) error {
	if card.Interaction == nil {
		return nil
	}
	b := *card.Interaction
	if messageID == "" || b.RequestID == "" || b.Principal.UserID == "" ||
		b.Principal.ChatID != rc.chatID || b.Principal.SessionKey != rc.sessionKey {
		return errors.New("invalid interaction binding")
	}
	if !p.acceptFixedRoute(b.Principal.UserID, rc.chatID) {
		return errors.New("unregistered interaction route")
	}
	actions := map[string]map[string]string{}
	add := func(value string, extra map[string]string) {
		if !strings.HasPrefix(value, "perm:") && !strings.HasPrefix(value, "askq:") {
			return
		}
		copy := map[string]string{}
		for k, v := range extra {
			copy[k] = v
		}
		actions[value] = copy
	}
	for _, element := range card.Elements {
		switch e := element.(type) {
		case core.CardActions:
			for _, button := range e.Buttons {
				add(button.Value, button.Extra)
			}
		case core.CardListItem:
			add(e.BtnValue, e.Extra)
		}
	}
	p.cardActionMsgMu.Lock()
	defer p.cardActionMsgMu.Unlock()
	if p.interactions == nil {
		p.interactions = map[string]cardInteraction{}
	}
	// Fixed environments have one session; legacy installations get a bounded
	// guard too. Eviction makes old cards inert, never answers a newer question.
	if len(p.interactions) >= 128 {
		clear(p.interactions)
	}
	p.interactions[rc.sessionKey] = cardInteraction{messageID, b, actions}
	return nil
}

func (p *Platform) consumeInteraction(user, chat, message, session, action string) (string, map[string]any, bool) {
	p.cardActionMsgMu.Lock()
	defer p.cardActionMsgMu.Unlock()
	entry, ok := p.interactions[session]
	if !ok {
		return "", nil, false
	}
	extra, allowed := entry.actions[action]
	if !allowed || entry.messageID != message || entry.binding.Principal.UserID != user || entry.binding.Principal.ChatID != chat {
		return "", nil, false
	}
	delete(p.interactions, session)
	values := map[string]any{"action": action}
	for k, v := range extra {
		values[k] = v
	}
	return entry.binding.RequestID, values, true
}
